// DB tables (Drizzle) — re-exported but the row type for `plans` is renamed
// to avoid colliding with the Zod-derived `Plan` from ./plan.js (the DAG plan).
export {
  projects,
  teams,
  plans,
  tasks,
  runs,
  events,
  checkpoints,
  rateWindows,
  agents,
  agentThreads,
  agentMessages,
  threadParticipants,
  chatActions,
  workerRuns,
  modelRouterPriors,
  modelRouterSamples,
  trajectories,
  hookEvents,
  promptBundles,
  runSummaries,
  dodCriteria,
  runtimeReports,
  dodKindValues,
  runtimeReportVerdictValues,
  planStatusValues,
  taskStatusValues,
  runStatusValues,
  runOutcomeValues,
  runPausedReasonValues,
  agentModelValues,
  messageRoleValues,
  agentKindValues,
  participantRoleValues,
  chatActionKindValues,
  chatActionStatusValues,
  workerRunStatusValues,
  modelRouterRoleValues,
  modelRouterModelValues,
  modelRouterSampleOutcomeValues,
  // v1.9 Phase 0
  projectBriefs,
  changeRequests,
  projectStates,
  projectAgentOverrides,
  planKindValues,
  packageTargetValues,
  changeRequestStatusValues,
  changeRequestSourceValues,
} from './db.js';

export type {
  Project,
  NewProject,
  Team as TeamRow,
  NewTeam,
  Plan as PlanRow,
  NewPlan,
  Task,
  NewTask,
  Run,
  NewRun,
  HarnessEventRow,
  NewHarnessEventRow,
  Checkpoint,
  NewCheckpoint,
  RateWindow,
  NewRateWindow,
  Agent as AgentRow,
  NewAgent,
  AgentThread as AgentThreadRow,
  NewAgentThread,
  AgentMessage as AgentMessageRow,
  NewAgentMessage,
  ThreadParticipant as ThreadParticipantRow,
  NewThreadParticipant,
  ChatAction as ChatActionRow,
  NewChatAction,
  WorkerRun,
  NewWorkerRun,
  WorkerRunStatus,
  PlanStatus,
  TaskStatus,
  TaskRole,
  RunStatus,
  RunOutcome,
  RunPausedReason,
  AgentModel,
  AgentKind,
  ParticipantRole,
  ChatActionKind,
  ChatActionStatus,
  MessageRole as MessageRoleType,
  ModelRouterRole,
  ModelRouterModel,
  ModelRouterPrior,
  ModelRouterSample,
  ModelRouterSampleOutcome,
  Trajectory,
  NewTrajectory,
  HookEvent,
  NewHookEvent,
  PromptBundle,
  NewPromptBundle,
  RunSummary,
  NewRunSummary,
  DodCriterion,
  NewDodCriterion,
  DodKind,
  DodSpecJson,
  RuntimeReport,
  NewRuntimeReport,
  RuntimeReportVerdict,
  RuntimeEvidenceJson,
  // v1.9 Phase 0
  ProjectBrief,
  NewProjectBrief,
  ChangeRequest,
  NewChangeRequest,
  ChangeRequestStatus,
  ChangeRequestSource,
  ChangeRequestRectJson,
  ProjectState,
  NewProjectState,
  ProjectAgentOverride,
  NewProjectAgentOverride,
  PlanKind,
  PackageTarget,
} from './db.js';

// v1.9 Brief patch directive parsing
export { briefPatchSchema, parseBriefPatchFromText } from './brief.js';
export type { BriefPatch } from './brief.js';

// Plan DAG (Zod)
export {
  agentSpecSchema,
  taskNodeSchema,
  edgeSchema,
  teamSchema,
  planSchema,
  successCriteriaSchema,
  parsePlan,
  safeParsePlan,
  validateDag,
} from './plan.js';
export type {
  AgentSpec,
  TaskNode,
  Edge,
  Team,
  Plan,
  SuccessCriteria,
  Role,
  DagValidationResult,
} from './plan.js';

// Events (Zod)
export { harnessEventSchema, parseHarnessEvent, safeParseHarnessEvent } from './events.js';
export type { HarnessEvent, HarnessEventType } from './events.js';

// Team (Zod) — re-export shape helpers; row type is `TeamRow` from db.
export { parseTeam, safeParseTeam } from './team.js';

// Agents (Zod / Model B + Chat v2)
export {
  agentKindSchema,
  agentSchema,
  createAgentInputSchema,
  updateAgentInputSchema,
  agentThreadSchema,
  createThreadInputSchema,
  agentMessageSchema,
  messageRoleSchema,
  sendMessageInputSchema,
  sendMessageResponseSchema,
  participantRoleSchema,
  threadParticipantSchema,
  addParticipantInputSchema,
  consultDirectiveSchema,
  addMemberDirectiveSchema,
  createProjectDirectiveSchema,
  startRunDirectiveSchema,
  directiveSchema,
} from './agents.js';
export type {
  Agent,
  CreateAgentInput,
  UpdateAgentInput,
  AgentThread,
  CreateThreadInput,
  AgentMessage,
  MessageRole,
  SendMessageInput,
  SendMessageResponse,
  ThreadParticipant,
  AddParticipantInput,
  ManagerDirective,
} from './agents.js';
