// The full product-tour timeline — the single source of truth for pacing.
//
// Every narrated scene is sized from its voice-over clip (src/vo-meta.ts, which
// is regenerated by scripts/make-voice.mjs), so the visuals can never drift out
// of sync with the audio. Chapter cards and the bookends use fixed lengths.
// Scenes overlap by TRANSITION frames (TransitionSeries in Promo.tsx).
import { COLORS } from './theme';
import { VO_FRAMES } from './vo-meta';
import type { Token } from './components/KineticText';

export const TRANSITION = 16; // overlap between adjacent scenes

const LEAD_IN = 12; // frames before the VO starts inside a scene
const TAIL = 22; // hold after the VO ends
const CHAPTER = 60; // act-divider card length
const MIN_TOUR = 140; // floor so short lines still breathe
const HOOK_TAIL = 38; // brand hold
const CTA_TAIL = 180; // long hold so the install commands + links stay readable

// Per-act accent colours give each chapter its own identity.
const A = {
  brand: COLORS.coral,
  mc: COLORS.coral,
  crew: COLORS.amber,
  plan: COLORS.blue,
  run: COLORS.green,
  collab: COLORS.coralBright,
  learn: COLORS.gold,
} as const;

export type TransKind =
  | { type: 'fade' }
  | { type: 'slide'; dir: 'from-left' | 'from-right' | 'from-top' | 'from-bottom' }
  | null;

type Raw =
  | { kind: 'hook'; vo: number }
  | { kind: 'problem'; vo: number }
  | { kind: 'cta'; vo: number }
  | { kind: 'build'; vo: number } // animated complete-run kanban centrepiece
  | { kind: 'chapter'; index: string; title: Token[]; accent: string }
  | {
      kind: 'design'; // cross-fade two screenshots (device switch / redesign)
      vo: number;
      srcA: string;
      srcB: string;
      labelA: string;
      labelB: string;
      eyebrow: string;
      title: Token[];
      browserTitle: string;
      accent: string;
      portrait?: boolean;
    }
  | {
      kind: 'tour';
      vo: number;
      screenshot: string;
      browserTitle: string;
      eyebrow: string;
      title: Token[];
      chips: string[];
      accent: string;
      portrait?: boolean;
    };

export type Scene = Raw & {
  id: string;
  start: number;
  dur: number;
  trans: TransKind; // transition that FOLLOWS this scene
  voSrc?: string;
  voFrom?: number;
  voDur?: number;
};

const tt = (a: string, b: string, c: string): Token[] => [{ t: a }, { t: b, c }];

// Ordered scene list. VO index === position in src/vo-meta.ts.
const RAW: Raw[] = [
  { kind: 'hook', vo: 0 },
  { kind: 'problem', vo: 1 },

  { kind: 'chapter', index: '01', title: tt('See ', 'everything.', A.mc), accent: A.mc },
  {
    kind: 'tour',
    vo: 2,
    screenshot: 'mission-control.png',
    browserTitle: 'localhost:4400 · Mission Control',
    eyebrow: 'Mission Control',
    title: tt('Your ', 'command center.', A.mc),
    chips: ['Live runs & agents', 'Token throughput', 'Outcomes at a glance'],
    accent: A.mc,
  },

  { kind: 'chapter', index: '02', title: tt('Build your ', 'crew.', A.crew), accent: A.crew },
  {
    kind: 'tour',
    vo: 3,
    screenshot: 'agents.png',
    browserTitle: 'localhost:4400 · Agents',
    eyebrow: 'Agents',
    title: tt('A roster of ', 'specialists.', A.crew),
    chips: ['Built-in team', 'Bring your own', 'Model & tools per agent'],
    accent: A.crew,
  },
  {
    kind: 'tour',
    vo: 4,
    screenshot: 'team-builder.png',
    browserTitle: 'localhost:4400 · Team Builder',
    eyebrow: 'Team Builder',
    title: tt('Compose your ', 'team.', A.crew),
    chips: ['Roles & models', 'Tools & prompts', 'Cost up front'],
    accent: A.crew,
  },

  { kind: 'chapter', index: '03', title: tt('Plan the ', 'work.', A.plan), accent: A.plan },
  {
    kind: 'tour',
    vo: 5,
    screenshot: 'project-detail.png',
    browserTitle: 'localhost:4400 · TipJar',
    eyebrow: 'Project',
    title: tt('Every project, ', 'briefed.', A.plan),
    chips: ['Goal & brief', 'Team', 'Definition of done'],
    accent: A.plan,
  },
  {
    kind: 'tour',
    vo: 6,
    screenshot: 'plan-editor.png',
    browserTitle: 'localhost:4400 · Plan Editor',
    eyebrow: 'Plan Editor',
    title: tt('A plan you can ', 'see.', A.plan),
    chips: ['Visual task DAG', 'Dependencies', 'Lock & run'],
    accent: A.plan,
  },
  {
    kind: 'tour',
    vo: 7,
    screenshot: 'goal-planner.png',
    browserTitle: 'localhost:4400 · Goal Planner',
    eyebrow: 'Goal Planner',
    title: tt('Planning, in a ', 'sandbox.', A.plan),
    chips: ['Goal-oriented', 'Cost-aware', 'Live preview'],
    accent: A.plan,
  },

  { kind: 'chapter', index: '04', title: tt('Run it ', 'live.', A.run), accent: A.run },
  {
    kind: 'tour',
    vo: 8,
    screenshot: 'run-view.png',
    browserTitle: 'localhost:4400 · Run · TipJar',
    eyebrow: 'Run',
    title: tt('Watch it ', 'run.', A.run),
    chips: ['Pending → done', 'Release gates', 'Resource budgets'],
    accent: A.run,
  },
  { kind: 'build', vo: 9 }, // the complete run, animated kanban end-to-end
  {
    kind: 'tour',
    vo: 10,
    screenshot: 'focusboard-preview.png',
    browserTitle: 'localhost:4400 · Focusboard — Preview',
    eyebrow: 'Live preview',
    title: tt('Preview, ', 'in the dashboard.', A.run),
    chips: ['Boots in the harness', 'The real app', 'Auto-refresh'],
    accent: A.run,
  },
  {
    kind: 'tour',
    vo: 11,
    screenshot: 'preview-box.png',
    browserTitle: 'localhost:4400 · Focusboard — Preview',
    eyebrow: 'Live preview',
    title: tt('The real, ', 'running app.', A.run),
    chips: ['Fully interactive', 'Desktop · tablet · mobile', 'Edit & reload'],
    accent: A.run,
    portrait: true,
  },
  {
    kind: 'design',
    vo: 12,
    srcA: 'focusboard-preview.png',
    srcB: 'focusboard-mobile.png',
    labelA: 'desktop',
    labelB: 'mobile',
    eyebrow: 'Responsive',
    title: tt('Desktop or ', 'mobile.', A.run),
    browserTitle: 'localhost:4400 · Focusboard — Preview',
    accent: A.run,
  },
  {
    kind: 'tour',
    vo: 13,
    screenshot: 'focusboard-iterate.png',
    browserTitle: 'localhost:4400 · Focusboard — Changes',
    eyebrow: 'Iterate',
    title: tt('Change design, ', 'add features.', A.run),
    chips: ['Point & click', 'Design + features', 'Run iteration'],
    accent: A.run,
  },
  {
    kind: 'design',
    vo: 14,
    srcA: 'preview-box.png',
    srcB: 'preview-box-light.png',
    labelA: 'before',
    labelB: 'after',
    eyebrow: 'Updated',
    title: tt('The preview ', 'updates.', A.run),
    browserTitle: 'localhost:4400 · Focusboard — Preview',
    accent: A.run,
    portrait: true,
  },

  { kind: 'chapter', index: '05', title: tt('Work ', 'together.', A.collab), accent: A.collab },
  {
    kind: 'tour',
    vo: 15,
    screenshot: 'chat.png',
    browserTitle: 'localhost:4400 · Team Chat',
    eyebrow: 'Team Chat',
    title: tt('Brief them in ', 'plain words.', A.collab),
    chips: ['Plain-language briefs', 'Directives → action', 'Threaded'],
    accent: A.collab,
  },
  {
    kind: 'tour',
    vo: 16,
    screenshot: 'skills.png',
    browserTitle: 'localhost:4400 · Skills',
    eyebrow: 'Skills',
    title: tt('Skills, ', 'built in.', A.collab),
    chips: ['audit · harden · polish', 'Seed, project & user', 'One click'],
    accent: A.collab,
  },
  {
    kind: 'tour',
    vo: 17,
    screenshot: 'workers.png',
    browserTitle: 'localhost:4400 · Workers',
    eyebrow: 'Workers',
    title: tt('Workers on ', 'demand.', A.collab),
    chips: ['Standalone jobs', 'On demand', 'Run history'],
    accent: A.collab,
  },

  { kind: 'chapter', index: '06', title: tt('Learn & ', 'control.', A.learn), accent: A.learn },
  {
    kind: 'tour',
    vo: 18,
    screenshot: 'insights.png',
    browserTitle: 'localhost:4400 · Insights',
    eyebrow: 'Insights',
    title: tt('Learn from every ', 'run.', A.learn),
    chips: ['Trajectories', 'Summaries', 'Router priors'],
    accent: A.learn,
  },
  {
    kind: 'tour',
    vo: 19,
    screenshot: 'prompt-bundles.png',
    browserTitle: 'localhost:4400 · Prompt Bundles',
    eyebrow: 'Prompt Bundles',
    title: tt('Context, ', 'versioned.', A.learn),
    chips: ['Reusable context', 'Versioned', 'Cost per bundle'],
    accent: A.learn,
  },
  {
    kind: 'tour',
    vo: 20,
    screenshot: 'settings.png',
    browserTitle: 'localhost:4400 · Settings',
    eyebrow: 'Settings',
    title: tt('Yours to ', 'control.', A.learn),
    chips: ['Theme & language', 'Data management', 'Full control'],
    accent: A.learn,
  },

  { kind: 'cta', vo: 21 },
];

function durOf(r: Raw): number {
  switch (r.kind) {
    case 'chapter':
      return CHAPTER;
    case 'hook':
      return LEAD_IN + VO_FRAMES[r.vo] + HOOK_TAIL;
    case 'cta':
      return LEAD_IN + VO_FRAMES[r.vo] + CTA_TAIL;
    case 'problem':
      return LEAD_IN + VO_FRAMES[r.vo] + TAIL;
    case 'tour':
    case 'build':
    case 'design':
      return Math.max(MIN_TOUR, LEAD_IN + VO_FRAMES[r.vo] + TAIL);
  }
}

// A clean forward slide between content beats; gentle fades around chapter cards.
function transBetween(cur: Raw, nxt: Raw): TransKind {
  if (cur.kind === 'chapter' || nxt.kind === 'chapter') return { type: 'fade' };
  return { type: 'slide', dir: 'from-right' };
}

function build(): Scene[] {
  const out: Scene[] = [];
  let cursor = 0;
  RAW.forEach((r, i) => {
    const dur = durOf(r);
    const start = cursor;
    const trans: TransKind = i < RAW.length - 1 ? transBetween(r, RAW[i + 1]) : null;
    const scene: Scene = { ...r, id: `${i}-${r.kind}`, start, dur, trans };
    if ('vo' in r) {
      scene.voSrc = `audio/vo/vo-${r.vo + 1}.wav`;
      scene.voFrom = start + LEAD_IN;
      scene.voDur = VO_FRAMES[r.vo];
    }
    out.push(scene);
    // next scene begins TRANSITION frames before this one ends (overlap).
    cursor = start + dur - (i < RAW.length - 1 ? TRANSITION : 0);
  });
  return out;
}

export const SCENES: Scene[] = build();

export const TOTAL_FRAMES =
  RAW.reduce((sum, r) => sum + durOf(r), 0) - (RAW.length - 1) * TRANSITION;

// Background score. null = silent. The bundled wisp-theme.wav is the synthesised,
// license-free bed from scripts/make-music.mjs (regenerated to TOTAL_FRAMES).
export const MUSIC_SRC: string | null = 'audio/wisp-theme.wav';
