// AUTO-GENERATED by scripts/make-voice.mjs — do not edit by hand.
// Voice-over clip lengths (vo-1..vo-22.wav) at 30fps. scenes.config.ts
// sizes every narrated scene from these so visuals stay locked to the audio.
export const VO_FRAMES = [208, 131, 151, 152, 148, 131, 154, 144, 127, 270, 114, 115, 111, 133, 102, 129, 109, 117, 160, 104, 90, 131] as const;
export const VO_SECONDS = [6.91, 4.35, 5.02, 5.06, 4.91, 4.34, 5.11, 4.77, 4.21, 8.99, 3.79, 3.83, 3.7, 4.43, 3.38, 4.27, 3.61, 3.9, 5.31, 3.45, 2.97, 4.36] as const;
