// Generates the voice-over clips with Piper (offline neural TTS), one WAV per
// line. Requires the Piper binary + voice model under .tts/ (see README) — those
// are gitignored; the produced clips in public/audio/vo/ are committed so the
// project renders without re-running TTS.
//
// Also emits src/vo-meta.ts (clip lengths in frames @30fps) so the timeline in
// scenes.config.ts can size every scene to its narration automatically — audio
// and visuals can never drift out of sync.
//
// Usage:  node scripts/make-voice.mjs
import { execFileSync } from 'node:child_process';
import { mkdirSync, statSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const PIPER = resolve(ROOT, '.tts', 'piper', 'piper.exe');
const MODEL = resolve(ROOT, '.tts', 'models', 'en_US-ryan-high.onnx');
const OUT = resolve(ROOT, 'public', 'audio', 'vo');
const META = resolve(ROOT, 'src', 'vo-meta.ts');
const FPS = 30;
mkdirSync(OUT, { recursive: true });

// One line per beat, in composition order. Index here == VO index referenced by
// scenes.config.ts. Bookends first (Hook, Problem), then one line per dashboard
// tab in tour order, then the CTA.
export const LINES = [
  // 0  Hook  (— "Claude Code." given a sentence boundary so "code" is enunciated)
  'Meet WISP — the visual orchestrator for Claude Code. It turns a single assistant into a whole engineering team.',
  // 1  Problem
  "Building real software with AI shouldn't mean babysitting one endless chat.",
  // 2  Mission Control
  'It all begins at Mission Control: every run, every token, every outcome, live.',
  // 3  Agents
  'Start with built-in specialists, or design your own — each with its own model and tools.',
  // 4  Team Builder
  'Compose a team by role, set their prompts and permissions, and see the cost up front.',
  // 5  Project Detail
  'Give each project a goal, a crew, and a clear definition of done.',
  // 6  Plan Editor
  'WISP turns that goal into a visual plan: tasks, dependencies, and the order to build them.',
  // 7  Goal Planner
  'Curious how it plans? Explore the planner itself, in a live sandbox.',
  // 8  Run View
  'Then watch it run — every task moving across the board, from queued to done.',
  // 9  Build story — the complete run (TipJar ran as a dependency chain)
  "Here's a complete run. WISP works through the plan in isolated git worktrees, gates every result, retries what fails, and merges to main when it's green.",
  // 10 Live preview (focusboard)
  "When it's done, preview the live build right inside the dashboard.",
  // 11 Live app — interactive
  "There's the real, running app — live, and fully interactive.",
  // 12 Responsive — desktop / mobile
  'Check how it looks on desktop or mobile, without leaving the page.',
  // 13 Iterate — design + feature change requests
  'Click any element to request a change — a redesign, or a whole new feature.',
  // 14 Updated — preview reflects the change
  'Run an iteration, and the preview updates with the new design.',
  // 15 Team Chat
  'Brief your crew in plain language, and turn the conversation into real work.',
  // 16 Skills
  'Reusable skills — audit, harden, polish — come bundled in.',
  // 17 Workers
  'Fire off standalone workers for the smaller jobs, on demand.',
  // 18 Insights
  "Learn from every run: trajectories, summaries, and the router's own decision priors.",
  // 19 Prompt Bundles
  'Every prompt is captured as a reusable, versioned bundle.',
  // 20 Settings
  'And all of it is yours to configure and control.',
  // 21 CTA  ("install it" + a clean break so "With WISP." lands calmly, not rushed)
  'Just three commands to install it. Then start orchestrating. With WISP.',
];

function wavDurationSeconds(path) {
  const b = readFileSync(path);
  const sampleRate = b.readUInt32LE(24);
  const channels = b.readUInt16LE(22);
  const bits = b.readUInt16LE(34);
  const dataBytes = b.length - 44;
  return dataBytes / (sampleRate * channels * (bits / 8));
}

const seconds = [];
const frames = [];
LINES.forEach((text, i) => {
  const out = resolve(OUT, `vo-${i + 1}.wav`);
  execFileSync(PIPER, ['-m', MODEL, '-f', out, '--length_scale', '1.0', '--sentence_silence', '0.25'], {
    input: text,
    stdio: ['pipe', 'ignore', 'inherit'],
  });
  const dur = wavDurationSeconds(out);
  const fr = Math.ceil(dur * FPS);
  seconds.push(Number(dur.toFixed(2)));
  frames.push(fr);
  console.log(`vo-${i + 1}.wav  ${dur.toFixed(2)}s  ${fr}f  ${(statSync(out).size / 1024).toFixed(0)}KB  | ${text}`);
});

const totalVo = seconds.reduce((a, b) => a + b, 0);
writeFileSync(
  META,
  `// AUTO-GENERATED by scripts/make-voice.mjs — do not edit by hand.\n` +
    `// Voice-over clip lengths (vo-1..vo-${LINES.length}.wav) at ${FPS}fps. scenes.config.ts\n` +
    `// sizes every narrated scene from these so visuals stay locked to the audio.\n` +
    `export const VO_FRAMES = [${frames.join(', ')}] as const;\n` +
    `export const VO_SECONDS = [${seconds.join(', ')}] as const;\n`,
);

console.log(`\nVOICE DONE — ${LINES.length} clips, ${totalVo.toFixed(1)}s total VO`);
console.log(`wrote ${META}`);
