#!/usr/bin/env node
/**
 * Mock `claude` CLI for orchestrator subprocess tests.
 *
 * Behavior is selected via env vars (so we don't have to parse the real CLI's
 * flag set):
 *
 *   MOCK_MODE=ok           — emit text-delta + usage + completion, exit 0 (default)
 *   MOCK_MODE=fail         — emit some output, exit 1 with stderr "boom"
 *   MOCK_MODE=rate-limit   — print "rate limit exceeded" to stderr, exit 1
 *   MOCK_MODE=auth-fail    — print "credentials invalid" to stderr, exit 1
 *   MOCK_MODE=auth-ok      — exit 0 silently (auth probe success)
 *   MOCK_MODE=garbled      — emit a few non-JSON lines mixed with valid JSONL, exit 0
 *   MOCK_MODE=plan         — write a valid 3-node plan.json into cwd, emit a couple
 *                             of NDJSON events, exit 0 (used by F1 e2e harness mode).
 *   MOCK_MODE=task         — emit 3 text-delta + 1 tool-use + 1 usage, exit 0
 *                             (used by F1 for architect/developer/qa task slots).
 *   MOCK_MODE=usage-with-cache — emit a result frame with cache_creation tokens, exit 0
 *                             (used to test cache-token summing in the parser).
 *   MOCK_MODE=session-id   — emit a leading frame containing session_id, then ok-style
 *                             events. Verifies the subprocess parser captures session_id
 *                             on first sight and emits task.session-id once.
 *
 * Reads stdin (drains it) so callers writing the prompt don't block.
 */

import fs from 'node:fs';
import path from 'node:path';
import { stdin } from 'node:process';

const mode = process.env.MOCK_MODE ?? 'ok';

// Drain stdin to unblock the parent.
stdin.resume();
let stdinClosed = false;
stdin.on('end', () => {
  stdinClosed = true;
});
stdin.on('data', () => {});

function emit(obj) {
  process.stdout.write(JSON.stringify(obj) + '\n');
}

async function waitForStdin() {
  // Wait briefly for stdin so we approximate real CLI behavior.
  for (let i = 0; i < 20 && !stdinClosed; i++) {
    await new Promise((r) => setTimeout(r, 5));
  }
}

(async () => {
  await waitForStdin();

  switch (mode) {
    case 'ok':
      emit({ type: 'text-delta', text: 'Hello ' });
      emit({ type: 'text-delta', text: 'world' });
      emit({ type: 'tool-use', tool: 'Read', input: { path: '/tmp/x' } });
      emit({
        type: 'result',
        subtype: 'success',
        num_turns: 1,
        usage: {
          input_tokens: 12,
          cache_creation_input_tokens: 0,
          cache_read_input_tokens: 0,
          output_tokens: 7,
        },
      });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    case 'fail':
      emit({ type: 'text-delta', text: 'partial' });
      process.stderr.write('boom\n');
      process.exit(1);
      break;
    case 'rate-limit':
      process.stderr.write('Error: rate limit exceeded\n');
      process.exit(1);
      break;
    case 'auth-fail':
      process.stderr.write('credentials invalid; please run claude login\n');
      process.exit(1);
      break;
    case 'auth-ok':
      emit({ type: 'text-delta', text: 'hi' });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    case 'garbled':
      process.stdout.write('not json\n');
      emit({ type: 'text-delta', text: 'ok' });
      process.stdout.write('{ broken json\n');
      emit({ type: 'unknown-thing', foo: 'bar' });
      process.exit(0);
      break;
    case 'plan': {
      // Write a valid 3-node DAG plan.json into cwd.
      const filler = 'x'.repeat(64);
      const team = {
        roles: [
          {
            role: 'architect',
            model: 'opus',
            allowedTools: ['Read'],
            systemPrompt: `mock architect ${filler}`,
          },
          {
            role: 'developer',
            model: 'sonnet',
            allowedTools: ['Read', 'Edit'],
            systemPrompt: `mock developer ${filler}`,
          },
          {
            role: 'qa',
            model: 'sonnet',
            allowedTools: ['Read'],
            systemPrompt: `mock qa ${filler}`,
          },
        ],
      };
      const plan = {
        goal: 'mock plan generated by tests/fixtures/mock-claude.mjs',
        team,
        nodes: [
          {
            id: 'architect',
            role: 'architect',
            prompt: 'design the system',
            deps: [],
            successCriteria: { custom: 'node -e "process.exit(0)"' },
            maxTurns: 10,
          },
          {
            id: 'developer',
            role: 'developer',
            prompt: 'implement the design',
            deps: ['architect'],
            successCriteria: { custom: 'node -e "process.exit(0)"' },
            maxTurns: 10,
          },
          {
            id: 'qa',
            role: 'qa',
            prompt: 'verify the implementation',
            deps: ['developer'],
            successCriteria: { custom: 'node -e "process.exit(0)"' },
            maxTurns: 10,
          },
        ],
        edges: [
          { from: 'architect', to: 'developer' },
          { from: 'developer', to: 'qa' },
        ],
      };
      try {
        fs.writeFileSync(path.join(process.cwd(), 'plan.json'), JSON.stringify(plan, null, 2));
      } catch (err) {
        process.stderr.write(`mock plan write failed: ${err}\n`);
        process.exit(2);
      }
      emit({ type: 'text-delta', text: 'planning…' });
      emit({
        type: 'result',
        subtype: 'success',
        num_turns: 1,
        usage: {
          input_tokens: 100,
          cache_creation_input_tokens: 0,
          cache_read_input_tokens: 0,
          output_tokens: 50,
        },
      });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    }
    case 'task':
      emit({ type: 'text-delta', text: 'hi' });
      emit({ type: 'text-delta', text: 'working' });
      emit({ type: 'tool-use', tool: 'Read', input: { path: 'README.md' } });
      emit({ type: 'text-delta', text: 'done' });
      emit({
        type: 'result',
        subtype: 'success',
        num_turns: 5,
        usage: {
          input_tokens: 42,
          cache_creation_input_tokens: 0,
          cache_read_input_tokens: 0,
          output_tokens: 18,
        },
      });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    case 'session-id':
      // Real claude -p surfaces session_id in a leading frame; we also accept
      // it on any later frame. Mock both: leading frame carries it, and so
      // does the result frame, so the parser's emit-once logic gets exercised.
      emit({ type: 'system', subtype: 'init', session_id: 'sess-abc-123' });
      emit({ type: 'text-delta', text: 'hi' });
      emit({
        type: 'result',
        subtype: 'success',
        num_turns: 1,
        session_id: 'sess-abc-123',
        usage: {
          input_tokens: 1,
          cache_creation_input_tokens: 0,
          cache_read_input_tokens: 0,
          output_tokens: 1,
        },
      });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    case 'usage-with-cache':
      emit({
        type: 'result',
        subtype: 'success',
        num_turns: 3,
        usage: {
          input_tokens: 6,
          cache_creation_input_tokens: 35447,
          cache_read_input_tokens: 0,
          output_tokens: 8,
        },
      });
      emit({ type: 'completion' });
      process.exit(0);
      break;
    default:
      process.stderr.write(`unknown MOCK_MODE: ${mode}\n`);
      process.exit(2);
  }
})();
